name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Senrism
          outputs: |
            dist/github-contribution-grid-snake.svg
          args: >
            --color_snake #00AAFF # Electric Blue for the snake's body
            --color_dots #1a1a1a,#2a2a2a,#4a4a4a,#6a6a6a # Dark sleek gray gradient for the background dots
            --color_contributions #FFAA00,#AA00FF # Optional: Bright orange and electric purple for active contributions if supported
            --pause 2

      - name: Commit & Push to the Repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generate snake animation [skip ci]" || echo "No changes to commit"
          git push
